<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\IOFactory;

class ReportesController extends Controller
{
    //
    public function exportPrueba(){
            // Create a new PhpWord object
        $phpWord = new PhpWord();

        // Add a new section to the document
        $section = $phpWord->addSection();

        // Add text to the section
        $section->addText('Hello, this is a sample Word document generated by PhpWord in Laravel 8!');
        $section->addText('Hello, this is a sample Word document generated by PhpWord in Laravel 8!');



        // Define the file name
        $fileName = 'sample.docx';

        // Save the file temporarily
        $temp_file = tempnam(sys_get_temp_dir(), $fileName);
        $objWriter = IOFactory::createWriter($phpWord, 'Word2007');
        $objWriter->save($temp_file);

        // Return the file as a response for download
        return response()->download($temp_file, $fileName)->deleteFileAfterSend(true);


    }
}
